services:
  bulletinboard.userservice.hosts:
    image: ${DOCKER_REGISTRY-}bulletinboarduserservicehosts
    build:
      context: .
      dockerfile: Src/UserService/BulletinBoard.UserService.Hosts/Dockerfile
    ports:
     - "8090:8080"
    networks:
      app_net:
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=postgre_user_db;Port=5432;Database=bulletinboard;Username=dbuser;Password=password
      - JWT__Issuer=BulletinBoard
      - JWT__Audience=BulletinBoard
      - JWT__Key=ultwreqqwddewQWDFAERHRTSDZFXCVBCKJSZFZra_string_guid_key87tg287hd8731g87qfwaua7q834wegfyloakwbpgfioewe
      - JWT__ExpiresIn=3600
      - Refresh__ExpiresIn=669600
    depends_on:
     - postgre_user_db

  bulletinboard.notificationservice.hosts:
    image: ${DOCKER_REGISTRY-}bulletinboardnotificationservicehosts
    build:
      context: .
      dockerfile: Src/NotificationService/BulletinBoard.NotificationService.Hosts/Dockerfile
    ports:
     - "8091:8080"
    networks:
      app_net:
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=postgre_notification_db;Port=5432;Database=bulletinboard;Username=dbuser;Password=password
      - JWT__Issuer=BulletinBoard
      - JWT__Audience=BulletinBoard
      - JWT__Key=ultwreqqwddewQWDFAERHRTSDZFXCVBCKJSZFZra_string_guid_key87tg287hd8731g87qfwaua7q834wegfyloakwbpgfioewe
      - JWT__ExpiresIn=3600
    depends_on:
     - postgre_notification_db

  postgre_user_db:
    image: postgres:17
    volumes:
      - user_db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bulletinboard
      PGDATA: /var/lib/postgresql/data
    networks:
      app_net: 
  
  postgre_notification_db:
    image: postgres:17
    volumes:
      - notification_db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bulletinboard
      PGDATA: /var/lib/postgresql/data
    networks:
      app_net: 
  
  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    networks:
      app_net:
    depends_on:
      - postgre_user_db
      - postgre_notification_db

networks:
  app_net:
    ipam:
      driver: default
      

volumes:
  user_db:
  notification_db: